
name: GitHub Actions - Práctica 7
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]
jobs:
  build-backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js v.18
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Yarn
      run: npm install --global yarn

    - name: Install backend dependencies
      run: cd backend && yarn install

    - name: Run backend tests
      run: cd backend && yarn test

    - name: Build backend
      run: cd backend && yarn build

  build-frontend:

    needs: build-backend

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js v.18
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Serve
      run: npm install --global serve

    - name: Install frontend dependencies and build
      run: cd frontend && npm install && npm run build